[profile.default]
src = "src"
out = "dApp/src/generated/abis"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
extra_output = ["abi"]
extra_output_files = ["abi"]
remappings = [
    "v4-core/=lib/v4-core/src/",
    "@uniswap/v4-core/=lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/src/",
    "solmate/=lib/solmate/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
