[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
remappings = [
    # Project-level dependencies
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "solmate/=lib/solmate/src/",
    "@uniswap/v4-core/=lib/v4-core/src/",
    "v4-core/test/=lib/v4-periphery/lib/v4-core/test/",
    "v4-core/=lib/v4-core/src/",
    "v4-periphery/=lib/v4-periphery/src/",
    "permit2/=lib/permit2/src/",

    # Nested dependencies for v4-periphery
    

    # Nested dependencies for v4-core (inside v4-periphery)
    "forge-std/src/=lib/v4-periphery/lib/v4-core/lib/forge-std/src/",
    "@openzeppelin/contracts/contracts/=lib/v4-periphery/lib/v4-core/lib/openzeppelin-contracts/contracts/",
    "solmate/src/=lib/v4-periphery/lib/v4-core/lib/solmate/src/",

    # Nested dependencies for permit2 (inside v4-periphery)
    "permit2/solmate/=lib/v4-periphery/lib/permit2/lib/solmate/src/",
    "permit2/openzeppelin-contracts/=lib/v4-periphery/lib/permit2/lib/openzeppelin-contracts/"
]

[profile.default.fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true